[functions]                                                                                  
   directory = "netlify/functions"                                                            
                                                                                               
 [functions.generateCurriculum]                                                               
   timeout = 25 
